repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    - id: autopep8
