# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots['RadarFrontendTestCase::test_empty_index 1'] = b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\n\n    <!-- Bootstrap CSS -->\n    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"\n          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">\n\n    <title>MLRE Radar</title>\n</head>\n<body class="d-flex flex-column h-100">\n<main role="main" class="flex-shrink-0">\n    <div id="content" class="container">\n        \n<h1 xmlns="http://www.w3.org/1999/html">MLRE Radar Overview</h1>\n<table class="table">\n    <thead>\n    <tr>\n        <th scope="col">#</th>\n        <th scope="col">Severity</th>\n        <th scope="col">Location</th>\n        <th scope="col">Description</th>\n        <th scope="col">Frequency</th>\n    </tr>\n    </thead>\n    <tbody>\n    \n    <tr>\n        <th>0</th>\n        <td>Severity.INFO</td>\n        <td>test_radar_common</td>\n        <td>This is a test event</td>\n        <td>2</td>\n    </tr>\n    \n    <tr>\n        <th>1</th>\n        <td>Severity.INFO</td>\n        <td>test_radar_common</td>\n        <td>This is another test event</td>\n        <td>2</td>\n    </tr>\n    \n    </tbody>\n</table>\n\n    </div>\n</main>\n<!-- Optional JavaScript -->\n<!-- jQuery first, then Popper.js, then Bootstrap JS -->\n<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"\n        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"\n        crossorigin="anonymous"></script>\n<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"\n        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"\n        crossorigin="anonymous"></script>\n<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"\n        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"\n        crossorigin="anonymous"></script>\n</body>\n</html>'
